### ISSUE TITLE
Code Error - Rewired + Cinemachine incompatibility

### ISSUE THREAD

**Issue by ItzELECTR0** [ItzELECTR0/TWAOS#1]
**Describe the problem**
Rewired incompatibility with Cinemachine update

File: Assets/Scripts/Game Logic/Play Logic/Rewired/Integration/Cinemachine/RewiredCinemachineBridge.cs

Errors:
Line 171 - Cannot find namespace "Cinemachine"
Line 219 - Cannot find namespace "Cinemachine"

**Comment by Macsito-prog** [comment]
Hey! Can I try and work on this? I'm learning C# at my work and this can surely help. Lmk what you think

**Comment by ItzELECTR0** [comment]
Temporary fix by removing the Cinemachine integration

**Comment by ItzELECTR0** [comment]
> Hey! Can I try and work on this? I'm learning C# at my work and this can surely help. Lmk what you think

Sure, you can create a pull request if you think you fixed it

**Comment by Macsito-prog** [comment]
> Sure, you can create a pull request if you think you fixed it

Thanks! I'll check it out tonight.

**Comment by ItzELECTR0** [comment]
Temporary fix by removing the Cinemachine integration, this has to be fixed by the Rewired developers themselves

**Comment by ItzELECTR0** [comment]
Temporary fix by removing the Cinemachine integration, this has to be fixed by the Rewired developers themselves
